version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "raolivei"
    labels:
      - "dependencies"
      - "javascript"

